### ISSUE TITLE
Build docker multi arch images for medical dashboard

### ISSUE THREAD

**Issue by cheyer** [dot-base/.github#17]
We need to update the `create-release.yml` and `create-pre-release.yml` seperatly in the medical dashboard as they do not reference the github actions in our `.github` repository, as e.g. the data graph:

```
  create-release:
    name: Create Release
    needs: merge-release-pr
    uses: dot-base/.github/.github/workflows/create-release.yml@master
    secrets:
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
```

This is mainly because the docker build command takes following arg in the medical dashboard:
```
--build-arg FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
```
